language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angularjs-module' ]; then cd .. && eval "mv $currentfolder generator-angularjs-module" && cd generator-angularjs-module; fi

